resource_types:
- name: mysql
  type: docker-image
  source:
    repository: brianmmcclain/mysql-concourse-resource
    tag: 0.0.1
resources:
- name: my-mysql
  type: mysql
  source:
        host: ((host))
        user: ((user))
        password: ((password))
        database: ((database))
        table: ((table))

jobs:
- name: hello-world
  plan:
  - get: my-mysql
    trigger: true
  - task: show-result
    config:
      inputs: 
      - name: my-mysql
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: cat 
        args: ["./my-mysql/concourse-mysql-resource.XXXXXX"]
  - put: my-mysql
    params:
      column: processed
      value: true